version: "3"
name: smartweather-application-layer

services:

  smart-weather-api:
    build:
      context: .
      dockerfile: SmartWeather.Api/Dockerfile
    container_name: smart-weather-api
    ports:
      - "8080:8080"
    depends_on:
      - mysql-master
      - mysql-proxy
    networks:
      - smart-weather-network

  smart-weather-historian:
    container_name: smart-weather-historian
    build:
      context: .
      dockerfile: SmartWeather.Historian/Dockerfile
    ports:
      - "8090:8090"
    depends_on:
      - mysql-master
      - mysql-proxy
    networks:
      - smart-weather-network

networks:
  smart-weather-network:
    driver: bridge