version: "3"
name: smartweather-project

services:

  smart-weather-api:
    build:
      context: ./..
      dockerfile: ./Application/SmartWeather.Api/Dockerfile
    container_name: smart-weather-api
    ports:
      - "8081:8081"
    environment:
      ADMIN_USERNAME : "lucas"
      ADMIN_MAIL : "chapuis863@gmail.com"
      ADMIN_PASSWORD : "12345"
    depends_on:
      mysql-master:
        condition: service_healthy
      mysql-slave-1:
        condition: service_healthy
      mysql-slave-2:
        condition: service_healthy
      kafka-0:
        condition: service_healthy
      kafka-1:
        condition: service_healthy
      kafka-2:
        condition: service_healthy
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 5
    networks:
      - smart-weather-network

  smart-weather-historian:
    container_name: smart-weather-historian
    build:
      context: ./..
      dockerfile: ./Application/SmartWeather.Historian/Dockerfile
    ports:
      - "8090:8090"
    depends_on:
      mysql-master:
        condition: service_healthy
      mysql-slave-1:
        condition: service_healthy
      mysql-slave-2:
        condition: service_healthy
      kafka-0:
        condition: service_healthy
      kafka-1:
        condition: service_healthy
      kafka-2:
        condition: service_healthy
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 5
    networks:
      - smart-weather-network

  smart-weather-socket-api:
    container_name: smart-weather-socket-api
    build:
      context: ./..
      dockerfile: ./Application/SmartWeather.Socket.Api/Dockerfile
    ports:
      - "8093:8093"
    depends_on:
      mysql-master:
        condition: service_healthy
      mysql-slave-1:
        condition: service_healthy
      mysql-slave-2:
        condition: service_healthy
      kafka-0:
        condition: service_healthy
      kafka-1:
        condition: service_healthy
      kafka-2:
        condition: service_healthy
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 5
    networks:
      - smart-weather-network

networks:
  smart-weather-network:
    driver: bridge