version: "3"
name: smartweather-project

services:

  smart-weather-api:
    build:
      context: .
      dockerfile: SmartWeather.Api/Dockerfile
    container_name: smart-weather-api
    ports:
      - "8081:8081"
    depends_on:
      - mysql-master
      - mysql-proxy
      - kafka-0
      - kafka-1
      - kafka-2
    networks:
      - smart-weather-network

  smart-weather-historian:
    container_name: smart-weather-historian
    build:
      context: .
      dockerfile: SmartWeather.Historian/Dockerfile
    ports:
      - "8090:8090"
    depends_on:
      - mysql-master
      - mysql-proxy
      - kafka-0
      - kafka-1
      - kafka-2
    networks:
      - smart-weather-network

  smart-weather-socket-api:
    container_name: smart-weather-socket-api
    build:
      context: .
      dockerfile: SmartWeather.Socket.Api/Dockerfile
    ports:
      - "8093:8093"
    depends_on:
      - mysql-master
      - mysql-proxy
      - kafka-0
      - kafka-1
      - kafka-2
    networks:
      - smart-weather-network

networks:
  smart-weather-network:
    driver: bridge