version: "3"
services:

  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: mosquitto
    ports:
      - 1883:1883
    volumes:
      - ./conf:/mosquitto/config
    networks:
      - smart-weather-network

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: root
    container_name: sqlserver
    environment:
      - "ACCEPT_EULA=Y"
      - "MSSQL_SA_PASSWORD=Password123!"
    ports:
      - 1433:1433
    volumes:
      - ./data:/var/opt/mssql/data
      - ./log:/var/opt/mssql/log
      - ./secrets:/var/opt/mssql/secrets
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "Password123!" -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s
    networks:
      - smart-weather-network
  
  smart-weather-api:
    build:
      context: .
      dockerfile: SmartWeather.Api/Dockerfile
    container_name: smart-weather-api
    ports:
      - "8080:8080"
    depends_on:
      sqlserver:
        condition: service_healthy
    networks:
      - smart-weather-network

volumes:
  sqlserver_data:
  

networks:
  smart-weather-network:
    driver: bridge