apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch-deployment
  namespace: smartweather-persistence
  labels:
    app: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  # strategy:
  #   type: Recreate
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
          name: elasticsearch
          resources:
            requests:
              memory: "2Gi"
              cpu: "500m"
            limits:
              memory: "4Gi"
              cpu: "1"
          env:
            - name: ES_JAVA_OPTS
              value: -Xms512m -Xmx512m
            - name: bootstrap.memory_lock
              value: "true"
            - name: discovery.type
              value: single-node
            - name: http.port
              value: "9230"
            - name: network.host
              value: 0.0.0.0
            - name: xpack.security.enabled
              value: "false"
          ports:
            - containerPort: 9230
              protocol: TCP
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: es-data
      restartPolicy: Always
      volumes:
        - name: es-data
          persistentVolumeClaim:
            claimName: es-data
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-service
  namespace: smartweather-persistence
spec:
  selector:
    app: elasticsearch
  ports:
    - protocol: TCP
      port: 9230
      targetPort: 9230
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    volume: es-data
  name: es-data
  namespace: smartweather-persistence
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 200Mi
