version: "3.9"
name: smartweather-project

services:

  smart-weather-station-mocker:
    container_name: smart-weather-station-mocker
    build:
      context: ./..
      dockerfile: Acquisition/SmartWeather.StationMocker/Dockerfile
    environment:
      STATION_NB : 50
      DATA_FREQ : 980
      ADMIN_TOKEN: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIxIiwiZW1haWwiOiJhZG1pbkBzbWFydHdlYXRoZXIubmV0Iiwicm9sZSI6IjEiLCJuYmYiOjE3MzQwOTY5NjEsImV4cCI6MTczNDEwNzc2MSwiaWF0IjoxNzM0MDk2OTYxLCJpc3MiOiJTbWFydFdlYXRoZXIiLCJhdWQiOiJTbWFydFdlYXRoZXIifQ.-V6Sy-nPzX3MwLoQVhF5ZBUmd_HQvHtanyEaq48gfO4"
    depends_on:
      - smart-weather-api
      - mysql-master
      - mysql-proxy
      - hivemq-proxy
      - kafka-0
      - kafka-1
      - kafka-2
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 5
    networks:
      - smart-weather-network

networks:
  smart-weather-network:
    driver: bridge
