version: "3.9"
name: smartweather-project

services:

  smart-weather-station-mocker:
    container_name: smart-weather-station-mocker
    build:
      context: ./..
      dockerfile: Acquisition/SmartWeather.StationMocker/Dockerfile
    environment:
      STATION_NB : 50
      DATA_FREQ : 980
      ADMIN_TOKEN: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIxIiwiZW1haWwiOiJhZG1pbkBzbWFydHdlYXRoZXIubmV0Iiwicm9sZSI6IkFkbWluIiwibmJmIjoxNzMzOTkyODgzLCJleHAiOjE3MzQwMDM2ODMsImlhdCI6MTczMzk5Mjg4MywiaXNzIjoiU21hcnRXZWF0aGVyIiwiYXVkIjoiU21hcnRXZWF0aGVyIn0.v3rWWJtreIiS1XJoNftgigq9Tj6izWxVsZWS-dfUjBE"
    depends_on:
      - smart-weather-api
      - mysql-master
      - mysql-proxy
      - hivemq-proxy
      - kafka-0
      - kafka-1
      - kafka-2
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 5
    networks:
      - smart-weather-network

networks:
  smart-weather-network:
    driver: bridge
