version: "3.9"
name: smartweather-project

services:

  smart-weather-station-mocker:
    container_name: smart-weather-station-mocker
    build:
      context: ./..
      dockerfile: Acquisition/SmartWeather.StationMocker/Dockerfile
    environment:
      API_URL: "http://smart-weather-api:8081/api/Station/Update"
      MAX_ERROR_RATE: 0
      STATION_NB : 50
      DATA_FREQ : 980
      ADMIN_TOKEN: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIxIiwiZW1haWwiOiJhZG1pbkBzbWFydHdlYXRoZXIubmV0Iiwicm9sZSI6IjEiLCJuYmYiOjE3MzY0OTgyNjQsImV4cCI6MTczNjUwOTA2NCwiaWF0IjoxNzM2NDk4MjY0LCJpc3MiOiJTbWFydFdlYXRoZXIiLCJhdWQiOiJTbWFydFdlYXRoZXIifQ.7C60ySvYjZwfuNa-6j72m3CuDa08aGc9uUF60NDrGrM"
    depends_on:
      - smart-weather-api
      - mysql-master
      - hivemq-proxy
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 5
    networks:
      - smart-weather-network

networks:
  smart-weather-network:
    driver: bridge
