version: "3.9"
name: smartweather-project

services:

  smart-weather-station-mocker:
    container_name: smart-weather-station-mocker
    build:
      context: ./..
      dockerfile: Acquisition/SmartWeather.StationMocker/Dockerfile
    environment:
      API_URL: "http://smart-weather-api:8081/api/Station/Update"
      MAX_ERROR_RATE: 0
      STATION_NB : 50
      DATA_FREQ : 980
      ADMIN_TOKEN: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIxIiwiZW1haWwiOiJhZG1pbkBzbWFydHdlYXRoZXIubmV0Iiwicm9sZSI6IjEiLCJuYmYiOjE3MzQ2OTk5MzgsImV4cCI6MTczNDcxMDczOCwiaWF0IjoxNzM0Njk5OTM4LCJpc3MiOiJTbWFydFdlYXRoZXIiLCJhdWQiOiJTbWFydFdlYXRoZXIifQ.tivrxk1MSi6NDBmOqtTYbD6ft0umcExNsvSNk9S4f7o"
    depends_on:
      - smart-weather-api
      - mysql-master
      - mysql-proxy
      - hivemq-proxy
      - kafka-0
      - kafka-1
      - kafka-2
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 5
    networks:
      - smart-weather-network

networks:
  smart-weather-network:
    driver: bridge
