version: "3.9"

services:
  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.2
    container_name: kibana
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9230
    ports:
      - 5601:5601
    networks:
      - smart-weather-network

networks:
  smart-weather-network:
    driver: bridge
