apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kibana
  name: kibana
  namespace: smartweather-presentation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - image: docker.elastic.co/kibana/kibana:8.10.2
          name: kibana
          resources:
            requests:
              memory: "2Gi"
              cpu: "500m"
            limits:
              memory: "4Gi"
              cpu: "1"
          env:
            - name: NODE_OPTIONS
              value: "--max-old-space-size=4096"
            - name: ELASTICSEARCH_HOSTS
              value: http://elasticsearch-service:9230
          ports:
            - containerPort: 5601
              protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: kibana-service
spec:
  ports:
    - name: "5601"
      port: 5601
      targetPort: 5601
      nodePort: 31000
  type: NodePort
  selector:
    app: kibana
