version: "3.9"
name: mysql-cluster

services:
  mysql-proxy:
    container_name: mysql-proxy
    image: haproxy:latest
    ports:
      - "3307:3307"
    volumes:
      - ./conf/mysql_proxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    depends_on:
      - mysql-master
      - mysql-slave-1
      - mysql-slave-2
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 5
    networks:
      - smart-weather-network

  mysql-master:
    image: mysql:5.7
    container_name: mysql-master
    user: root
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: smartweather
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - mysql-master-data:/var/lib/mysql
      - ./conf/maria_master.cnf:/etc/mysql/my.cnf:r
      - ./conf/maria_init_master.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 5
    networks:
      - smart-weather-network

  mysql-slave-1:
    image: mysql:5.7
    container_name: mysql-slave-1
    user: root
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - mysql-slave-data-1:/var/lib/mysql
      - ./conf/maria_slave_1.cnf:/etc/mysql/my.cnf:r
      - ./conf/maria_init_slave.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 5
    networks:
      - smart-weather-network
    depends_on:
      - mysql-master

  mysql-slave-2:
    image: mysql:5.7
    container_name: mysql-slave-2
    user: root
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - mysql-slave-data-2:/var/lib/mysql
      - ./conf/maria_slave_2.cnf:/etc/mysql/my.cnf:r
      - ./conf/maria_init_slave.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 5
    networks:
      - smart-weather-network
    depends_on:
      - mysql-master

volumes:
  mysql-master-data:
  mysql-slave-data-1:
  mysql-slave-data-2:

networks:
  smart-weather-network:
    driver: bridge
