version: "3.9"
name: smartweather-project

include:
  - "./Kafka/kafka-ckuster.yml"
  - "./Mqtt/mosquitto.yml"
  # - "./Mqtt/hivemq-cluster.yml"

networks:
  smart-weather-network:
    driver: bridge
