name: libs-ci

on:
  push:
    paths:
      - libs/**

jobs:
  restore:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "8.0.x"

      - name: Restore dependencies
        run: dotnet restore ./libs/SmartWeather.CSharpLibraries.sln

  build:
    runs-on: ubuntu-latest
    needs: restore
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "8.0.x"

      - name: Build projects
        run: dotnet build --configuration Release ./libs/SmartWeather.CSharpLibraries.sln

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "8.0.x"

      - name: Run tests
        run: dotnet test --no-build --configuration Release --verbosity normal ./libs/SmartWeather.CSharpLibraries.sln
